### ISSUE TITLE
Support for "text edit mode"

### ISSUE THREAD

**Issue by juarezjx** [HadesArchitect/GrafanaCassandraDatasource#14]
Hi Aleks,

When creating a query I can see a button for "Toggle text edit mode".  When pressed a text editor does not pop up.  Is this feature available?

Thanks in advance.  Really appreciate any assistance.  Trying to avoid using Elassandra or InfluxDB to get direct to our Cassandra data.

Juan

![image](https://user-images.githubusercontent.com/29693044/82704806-33836f80-9c2b-11ea-9786-8efc368cb7ee.png)

**Comment by HadesArchitect** [comment]
Hello @juarezjx. Thank you for the message! This plugin is in early phase (0.1.7 so far) so this feature is simply not implemented yet. It's on the roadmap but at this point, I can't specify any particular timeframe to be implemented (expected to be in June 2020). The hard issue is, the plugin system was completely reworked in Grafana 7.0 so at this point, I don't know if I have to focus on 7.0 support first or on the features like that (#14) 

Regardless, this one is important and definitely to be implemented soon. Please let me know if you need any other features because it does help me to build a proper roadmap and understand community needs!

**Comment by HadesArchitect** [comment]
@juarezjx While this ticket is still in progress, ALLOW FILTERING support was added in version 0.2.0 for the query constructor

**Comment by HadesArchitect** [comment]
FYI @futuarmo

**Comment by HadesArchitect** [comment]
Fixed in #44, to be released in 0.3.0
